<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260408065331 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE pokemon_types (pkt_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pkt_name VARCHAR(15) NOT NULL, pkt_color VARCHAR(7) NOT NULL, PRIMARY KEY (pkt_id))');
        $this->addSql('CREATE TABLE pokemons (pkm_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pkm_name VARCHAR(160) NOT NULL, pkm_number INT DEFAULT NULL, PRIMARY KEY (pkm_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3FD8B03D72D46054 ON pokemons (pkm_number)');
        $this->addSql('CREATE TABLE pokemon_pokemon_types (ppt_pkm_id INT NOT NULL, ppt_pkt_id INT NOT NULL, PRIMARY KEY (ppt_pkm_id, ppt_pkt_id))');
        $this->addSql('CREATE INDEX IDX_4997DD6FAD6B506E ON pokemon_pokemon_types (ppt_pkm_id)');
        $this->addSql('CREATE INDEX IDX_4997DD6F807A487B ON pokemon_pokemon_types (ppt_pkt_id)');
        $this->addSql('CREATE TABLE reset_password_request (rpr_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, rpr_usr_id INT NOT NULL, PRIMARY KEY (rpr_id))');
        $this->addSql('CREATE INDEX IDX_7CE748A67D683ED ON reset_password_request (rpr_usr_id)');
        $this->addSql('CREATE TABLE "users" (usr_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, usr_email VARCHAR(180) NOT NULL, usr_roles JSON NOT NULL, usr_password VARCHAR(255) NOT NULL, usr_lastname VARCHAR(160) NOT NULL, usr_firstname VARCHAR(160) NOT NULL, usr_birthdate DATE NOT NULL, usr_registered_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, usr_is_verified BOOLEAN NOT NULL, PRIMARY KEY (usr_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "users" (usr_email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE pokemon_pokemon_types ADD CONSTRAINT FK_4997DD6FAD6B506E FOREIGN KEY (ppt_pkm_id) REFERENCES pokemons (pkm_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pokemon_pokemon_types ADD CONSTRAINT FK_4997DD6F807A487B FOREIGN KEY (ppt_pkt_id) REFERENCES pokemon_types (pkt_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748A67D683ED FOREIGN KEY (rpr_usr_id) REFERENCES "users" (usr_id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE pokemon_pokemon_types DROP CONSTRAINT FK_4997DD6FAD6B506E');
        $this->addSql('ALTER TABLE pokemon_pokemon_types DROP CONSTRAINT FK_4997DD6F807A487B');
        $this->addSql('ALTER TABLE reset_password_request DROP CONSTRAINT FK_7CE748A67D683ED');
        $this->addSql('DROP TABLE pokemon_types');
        $this->addSql('DROP TABLE pokemons');
        $this->addSql('DROP TABLE pokemon_pokemon_types');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('DROP TABLE "users"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
